theme: jekyll-theme-midnight
title: "Shreya, Sarah, Vivian, Giannina Project"
description: "Frank P Leuck and Judith Sherwood Leuck reunion site and blog."
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "Create Performance Task"
google_analytics:
